version: '3'
services:
  app_init:
    image: "node:9.10.0"
    links: [
      cc-vault_db,
      cc-vault_dynamo,
      cc-vault_api,
    ]
    entrypoint: "echo Containers successfully initialized."

  cc-vault_api:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8081:80"

  cc-vault_db:
    image: mysql:5.7
    ports:
      - 3314:3306
    restart: always
    volumes:
      - ./src/store/migrations/mysql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=my-secure-pw
      - MYSQL_DATABASE=ccvault
      - MYSQL_USER=ccvault
      - MYSQL_PASSWORD=my-secure-pw

  cc-vault_dynamo:
    image: tray/dynamodb-local
    ports:
      - 7778:7777
    command: -port 7777 -sharedDb -inMemory
    volumes:
      - ./src/store/migrations/dynamodb:/init
