#!/bin/bash

echo "* Starting wallet RPC 1..."
/usr/bin/electroneum-wallet-rpc --daemon-port 28081 --rpc-bind-port 28082 --testnet --wallet-file /data/wallet-1/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind
