#!/bin/bash

# :( https://github.com/monero-project/monero/issues/1763
# TODO rewrite to proper foreground mode after it get solved

echo "* Starting node 1..."
/usr/bin/electroneumd --detach --testnet --testnet-p2p-bind-port 28080 --testnet-rpc-bind-port 28081 --no-igd --hide-my-port --testnet-data-dir /data/node-1 --p2p-bind-ip 0.0.0.0 --log-level 0 --add-exclusive-node 0.0.0.0:38080 --rpc-bind-ip 0.0.0.0 --confirm-external-bind

s6-svc -d /var/run/s6/services/node-1
