#!/bin/bash

echo "* Starting wallet RPC 2..."
/usr/bin/electroneum-wallet-rpc --daemon-port 38081 --rpc-bind-port 38082 --testnet --wallet-file /data/wallet-2/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind